[tools]
go = "1.26"
gofumpt = "latest"
golangci-lint = "2.11"
lefthook = "2.1"
lychee = "0.23"
node = "lts"
typos = "1.45"

[tasks.setup]
description = "Setup the project"
run = '''
for dir in $(find . -name go.mod -exec dirname {} \;); do \
go -C "$dir" mod tidy; done
lefthook install
'''

[tasks."go:lint"]
description = "Lint Go files"
run = 'golangci-lint run $(find . -name go.mod -exec dirname {} \;)'

[tasks."go:fmt"]
description = "Format Go files"
run = 'gofumpt -l -w .'

[tasks."go:test"]
description = "Test Go"
run = '''for dir in $(find . -name go.mod -exec dirname {} \;); do \
go -C "$dir" test ./...; done
'''
